name: ci-pipeline
run-name: Running CI pipeline triggered by ${{ github.actor }}
on:
  pull_request:
    branches:
      - develop
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test && ls
